name: WordPress Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          # Commands to install dependencies (e.g., composer install, npm install)

      - name: Run Automated Tests
        run: |
          # Commands to run automated tests (e.g., phpunit, npm test)

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          # Commands to install dependencies (e.g., composer install, npm install)

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/wpsite
            git pull origin main
            chown -R www-data:www-data .
            # Additional commands to set up WordPress and ensure permissions, etc.
